allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': true
  '@swc/core': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js: true
  core-js-pure: true
  postman-code-generators: true
  tree-sitter: true
  tree-sitter-json: true
