allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@swc/core': true
  '@tree-sitter-grammars/tree-sitter-yaml': true
  core-js: false
  core-js-pure: false
  postman-code-generators: true
  tree-sitter: true
  tree-sitter-json: true
