/**
 * The monthly product update archive.
 *
 * Newest first, and listed explicitly rather than autogenerated: autogeneration sorts
 * ascending, and an archive whose top entry is four years old reads as abandoned.
 * `sidebar_position` could invert it, but only by putting a negative magic number in
 * every page's frontmatter -- an explicit list is the version a person can read.
 *
 * One entry per month. The monthly update job adds its own, directly under "index".
 */
module.exports = {
  updatesSidebar: ["index", "2026-09"],
};
