module.exports = {
  docs: [
    {
      type: "category",
      label: "Introduction",
      link: { type: "doc", id: "introduction/index" },
      items: [
        "introduction/keycloak",
        "introduction/open-source",
        "introduction/documentation",
      ],
    },
    {
      type: "category",
      label: "Getting Started",
      link: { type: "doc", id: "getting-started/index" },
      items: [
        "getting-started/dashboard",
        "getting-started/realm-configuration",
        "getting-started/customizing-ui",
        "getting-started/email",
        "getting-started/launch-checklist",
        "getting-started/sample",
      ],
    },
    {
      type: "category",
      label: "Dashboard (self-service)",
      link: { type: "doc", id: "self-service/index" },
      items: [
        "self-service/access",
        "self-service/dashboard-overview",
        "self-service/deployments",
        "self-service/your-organization",
        "self-service/dedicated-clusters",
        "self-service/create-a-cluster",
        "self-service/regions",
        "self-service/custom-domains",
        "self-service/observability",
        "self-service/resources",
        "self-service/restrictions",
        "self-service/environment-variables",
      ],
    },
    {
      type: "category",
      label: "Securing Applications",
      link: { type: "doc", id: "securing-applications/index" },
      items: [
        "securing-applications/django",
        {
          type: "doc",
          id: "securing-applications/native-apps",
          label: "Native - iOS/Android/macOS",
        },
        "securing-applications/springboot",
        "securing-applications/javascript",
        "securing-applications/react",
        "securing-applications/next",
        "securing-applications/vue",
        "securing-applications/nuxt",
        "securing-applications/remix",
        "securing-applications/sveltekit",
        "securing-applications/angular",
      ],
    },
    {
      type: "category",
      label: "API + Access",
      link: { type: "doc", id: "api/index" },
      items: ["api/service-accounts", "api/authentication", "api/sdks"],
    },
    {
      type: "category",
      label: "Authentication",
      link: { type: "doc", id: "authentication/index" },
      items: [
        "authentication/understanding-flows",
        "authentication/username-password",
        "authentication/social-login",
        "authentication/magic-links",
        "authentication/otps",
        "authentication/webauthn",
        "authentication/sso",
        "authentication/complex-flows",
      ],
    },
    {
      type: "category",
      label: "SSO",
      link: { type: "doc", id: "sso/index" },
      items: ["sso/setup", "sso/wizards", "sso/sso-without-auth"],
    },
    {
      type: "category",
      label: "Organizations",
      link: { type: "doc", id: "organizations/index" },
      items: [
        "organizations/attributes",
        "organizations/membership",
        "organizations/invitations",
        "organizations/roles",
        "organizations/idp-wizard",
        "organizations/identity-providers",
        { type: "doc", id: "admin-portal/index", label: "Admin Portal" },
        "organizations/token-mappers",
        "organizations/active-organization",
        "organizations/active-organization-authenticator",
        "organizations/organizations-import-export",
        "organizations/organizations-events",
      ],
    },
    {
      type: "category",
      label: "Admin Portal",
      link: { type: "doc", id: "admin-portal/index" },
      items: ["admin-portal/portal-link"],
    },
    {
      type: "category",
      label: "Audit Logs",
      link: { type: "doc", id: "audit-logs/index" },
      items: [
        "audit-logs/access",
        "audit-logs/admin",
        "audit-logs/system",
        "audit-logs/api",
        "audit-logs/webhooks",
      ],
    },
    {
      type: "category",
      label: "User Migration",
      link: { type: "doc", id: "user-migration/index" },
      items: ["user-migration/api"],
    },
    {
      type: "category",
      label: "Security",
      link: { type: "doc", id: "security/index" },
      items: [
        "security/password-blacklist",
        "security/password-policy",
        "security/brute-force-detection",
        "security/allow-deny-lists",
        "security/rate-limiting",
        "security/penetration-tests",
        "security/recaptcha",
      ],
    },
    {
      type: "category",
      label: "Hosting",
      link: { type: "doc", id: "hosting/index" },
      items: ["hosting/kubernetes", "hosting/connect"],
    },
    {
      type: "category",
      label: "Keycloak",
      link: { type: "doc", id: "keycloak/index" },
      items: [
        "keycloak/overview",
        "keycloak/ciam",
        "keycloak/iam",
        "keycloak/idp",
      ],
    },
  ],
};
