// GENERATED by scripts/gen-management-sidebar.mjs from the OpenAPI spec.
// Do not edit by hand -- run `pnpm regen-api-docs`.
module.exports = [
  {
    "type": "doc",
    "id": "management/phase-two-cluster-management-api"
  },
  {
    "type": "category",
    "label": "Organizations",
    "link": {
      "type": "doc",
      "id": "management/orgs"
    },
    "items": [
      {
        "type": "doc",
        "id": "management/org-list",
        "label": "List your organizations",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/org-api-secret-list",
        "label": "List API secrets for this organization",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/org-api-secret-create",
        "label": "Create an API secret for this organization",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/org-api-secret-count",
        "label": "Count API secrets for this organization",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/org-api-secret-detail",
        "label": "Get an API secret",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/org-api-secret-delete",
        "label": "Remove an API secret",
        "className": "api-method delete"
      }
    ]
  },
  {
    "type": "category",
    "label": "Billing",
    "link": {
      "type": "doc",
      "id": "management/billing"
    },
    "items": [
      {
        "type": "doc",
        "id": "management/org-billing-contact-list",
        "label": "List billing contacts for this organization",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/org-billing-contact-create",
        "label": "Add a billing contact",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/org-billing-contact-delete",
        "label": "Remove a billing contact",
        "className": "api-method delete"
      },
      {
        "type": "doc",
        "id": "management/org-payment-method-list",
        "label": "List payment methods for this organization",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/org-payment-method-setup-session-create",
        "label": "Create a Stripe Checkout link to add a payment method",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/org-payment-method-delete",
        "label": "Remove a payment method",
        "className": "api-method delete"
      },
      {
        "type": "doc",
        "id": "management/org-payment-method-set-default",
        "label": "Set this organization's default payment method",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/org-billing-portal-session-create",
        "label": "Create a Stripe billing portal session link",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/org-subscription-list",
        "label": "List subscriptions for this organization",
        "className": "api-method get"
      }
    ]
  },
  {
    "type": "category",
    "label": "Clusters",
    "link": {
      "type": "doc",
      "id": "management/clusters"
    },
    "items": [
      {
        "type": "doc",
        "id": "management/cluster-list",
        "label": "List your dedicated clusters",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-create",
        "label": "Create a dedicated cluster",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-name-availability-check",
        "label": "Check whether a cluster name is available",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-region-list",
        "label": "List regions available for dedicated clusters",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-detail",
        "label": "Get a dedicated cluster by ID",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-delete",
        "label": "Remove a dedicated cluster",
        "className": "api-method delete"
      },
      {
        "type": "doc",
        "id": "management/cluster-subscription-detail",
        "label": "Get subscription and billing information for a dedicated cluster",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-billing-session-create",
        "label": "Create a Stripe billing portal session link for a cluster",
        "className": "menu__list-item--deprecated api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-checkout-resume",
        "label": "Resume Stripe checkout for a cluster whose billing setup was not completed. Returns a link to complete payment setup within a browser",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-deployment-list",
        "label": "List deployments for a dedicated cluster",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-deployment-create",
        "label": "Create a deployment for a dedicated cluster",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-deployment-import",
        "label": "Create a deployment from a realm export",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-deployment-name-availability-check",
        "label": "Check whether a deployment name is available on a cluster",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-host-update",
        "label": "Change the cluster's primary hostname",
        "className": "api-method put"
      },
      {
        "type": "doc",
        "id": "management/cluster-metrics-detail",
        "label": "Get health metrics for a dedicated cluster",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-restart-status-detail",
        "label": "Check whether a cluster restart is in progress",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-system-info-detail",
        "label": "Get system info for a dedicated cluster",
        "className": "api-method get"
      }
    ]
  },
  {
    "type": "category",
    "label": "Deployments",
    "link": {
      "type": "doc",
      "id": "management/deployments"
    },
    "items": [
      {
        "type": "doc",
        "id": "management/deployment-detail",
        "label": "Get a deployment by ID",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/deployment-update",
        "label": "Update a deployment by ID",
        "className": "api-method put"
      },
      {
        "type": "doc",
        "id": "management/deployment-delete",
        "label": "Remove a deployment by ID",
        "className": "api-method delete"
      },
      {
        "type": "doc",
        "id": "management/deployment-app-link-create",
        "label": "Create an app link for a deployment",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/deployment-console-link-create",
        "label": "Create an admin console link for a deployment",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/deployment-metrics-detail",
        "label": "Get metrics for a deployment by ID",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/deployment-token-create",
        "label": "Exchange a token for a deployment access token",
        "className": "api-method post"
      }
    ]
  },
  {
    "type": "category",
    "label": "Custom Domains",
    "link": {
      "type": "doc",
      "id": "management/customer-domains"
    },
    "items": [
      {
        "type": "doc",
        "id": "management/cluster-domain-list",
        "label": "List custom domains for a cluster",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-domain-create",
        "label": "Add a custom domain to a cluster",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-domain-detail",
        "label": "Get a custom domain by ID",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-domain-delete",
        "label": "Remove a custom domain by ID",
        "className": "api-method delete"
      },
      {
        "type": "doc",
        "id": "management/cluster-domain-status-detail",
        "label": "Get a custom domain's provisioning status",
        "className": "api-method get"
      }
    ]
  },
  {
    "type": "category",
    "label": "Cluster Extensions",
    "link": {
      "type": "doc",
      "id": "management/extensions"
    },
    "items": [
      {
        "type": "doc",
        "id": "management/cluster-extension-list",
        "label": "List extensions for a cluster",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-create",
        "label": "Create an extension for a cluster",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-reconcile",
        "label": "Restart a cluster to apply extension changes",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-keycloak-version-list",
        "label": "List Keycloak major versions supported for extensions",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-detail",
        "label": "Get an extension by ID",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-update",
        "label": "Enable or disable an extension",
        "className": "api-method put"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-delete",
        "label": "Remove an extension by ID",
        "className": "api-method delete"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-standalone-upload-url-create",
        "label": "Create an upload URL for a standalone extension",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-standalone-confirm",
        "label": "Confirm a standalone extension upload",
        "className": "api-method put"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-version-create",
        "label": "Create a new extension version",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-version-delete",
        "label": "Remove an extension version by ID",
        "className": "api-method delete"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-version-confirm",
        "label": "Confirm an extension version upload",
        "className": "api-method put"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-version-upload-url-create",
        "label": "Create an upload URL for an extension version",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-extension-version-validate",
        "label": "Approve or reject an extension version",
        "className": "api-method put"
      },
      {
        "type": "doc",
        "id": "management/cluster-well-known-get",
        "label": "Get app association file state for a custom domain",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-well-known-change-password-set",
        "label": "Set the change-password redirect for a custom domain",
        "className": "api-method put"
      },
      {
        "type": "doc",
        "id": "management/cluster-well-known-delete",
        "label": "Remove an app association file from a custom domain",
        "className": "api-method delete"
      },
      {
        "type": "doc",
        "id": "management/cluster-well-known-confirm",
        "label": "Validate and publish an uploaded app association file",
        "className": "api-method put"
      },
      {
        "type": "doc",
        "id": "management/cluster-well-known-upload-url-create",
        "label": "Create an upload URL for an app association file",
        "className": "api-method post"
      }
    ]
  },
  {
    "type": "category",
    "label": "Environment Variables",
    "link": {
      "type": "doc",
      "id": "management/environment-variables"
    },
    "items": [
      {
        "type": "doc",
        "id": "management/cluster-env-var-list",
        "label": "List environment variables for a cluster",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-env-var-create",
        "label": "Add an environment variable to a cluster",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-env-var-detail",
        "label": "Get an environment variable by ID",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-env-var-update",
        "label": "Update an environment variable",
        "className": "api-method put"
      },
      {
        "type": "doc",
        "id": "management/cluster-env-var-delete",
        "label": "Remove an environment variable",
        "className": "api-method delete"
      }
    ]
  },
  {
    "type": "category",
    "label": "IP Rules",
    "link": {
      "type": "doc",
      "id": "management/ip-rules"
    },
    "items": [
      {
        "type": "doc",
        "id": "management/cluster-ip-rule-list",
        "label": "List IP rules for a cluster",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-ip-rule-update",
        "label": "Replace IP rules for a cluster",
        "className": "api-method post"
      },
      {
        "type": "doc",
        "id": "management/cluster-ip-rule-detail",
        "label": "Get an IP rule by ID",
        "className": "api-method get"
      }
    ]
  },
  {
    "type": "category",
    "label": "Logs",
    "link": {
      "type": "doc",
      "id": "management/logs"
    },
    "items": [
      {
        "type": "doc",
        "id": "management/cluster-log-list",
        "label": "List log files for a cluster",
        "className": "api-method get"
      },
      {
        "type": "doc",
        "id": "management/cluster-log-detail",
        "label": "Get a cluster log file",
        "className": "api-method get"
      }
    ]
  }
];
